name: Run Hello World

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  pytest: 
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        run: echo Hello from Worklow Template



    
  

    

    

